<link rel="stylesheet" type="text/css" href="/global/dt3/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css"/>
<?php $this->inlineScript()->appendFile('/global/dt3/assets/plugins/bootstrap-daterangepicker/moment.min.js'); ?>
<?php $this->inlineScript()->appendFile('/global/dt3/assets/plugins/bootstrap-daterangepicker/daterangepicker.js'); ?>

<?php $this->inlineScript()->captureStart(); ?>
var isSingleDatePicker = <?php echo (isset($type) && $type == 'date') ? 'true' : 'false'; ?>;


if( isSingleDatePicker ) {
	var options = {singleDatePicker: isSingleDatePicker};
} else {
	var options = {
            ranges: {
               'Today': [moment(), moment()],
               'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
               'Last 7 Days': [moment().subtract('days', 6), moment()],
               'Last 30 Days': [moment().subtract('days', 29), moment()],
               'This Month': [moment().startOf('month'), moment().endOf('month')],
               'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
            },
            opens: (App.isRTL() ? 'left' : 'right'),
            format: 'MM/dd/yyyy',
            separator: ' to ',
			startDate: moment().subtract('days', 29),
            endDate: moment(),            
            minDate: '01/01/2012',
            maxDate: '12/31/2014',
            locale: {
                applyLabel: 'Submit',
                fromLabel: 'From',
                toLabel: 'To',
                customRangeLabel: 'Custom Range',
                daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr', 'Sa'],
                monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
                firstDay: 1
            },
            showWeekNumbers: true,
            buttonClasses: ['btn btn-default-danger']
        }
    };

jQuery(document).ready(function(){
      $('#<?php echo $this->elementName; ?>').daterangepicker({singleDatePicker: isSingleDatePicker});
});
<?php $this->inlineScript()->captureEnd(); ?>

<div class="input-prepend input-group">
    <span class="add-on input-group-addon">
    	<i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
	</span>
	<input type="text" style="width: 200px" name="<?php echo $this->elementName; ?>" id="<?php echo $this->elementName; ?>" class="form-control" value="<?php echo $value; ?>" /> 
</div>