<link rel="stylesheet" type="text/css" href="/global/dt3/assets/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css"/>
<?php $this->inlineScript()->appendFile('/global/dt3/assets/plugins/bootstrap-daterangepicker/moment.min.js'); ?>
<?php $this->inlineScript()->appendFile('/global/dt3/assets/plugins/bootstrap-daterangepicker/daterangepicker.js'); ?>

<?php $this->inlineScript()->captureStart(); ?>
var isSingleDatePicker = <?php echo (isset($type) && $type == 'date') ? 'true' : 'false'; ?>;


if( isSingleDatePicker ) {
	var options = {singleDatePicker: isSingleDatePicker};
} else {
var options = {
    startDate: moment().subtract('days', 29),
    endDate: moment(),
    minDate: '01/01/2012',
    /*maxDate: '12/31/2014', */
    dateLimit: { days: 400 },
    showDropdowns: true,
    showWeekNumbers: true,
    timePicker: false,
    timePickerIncrement: 1,
    timePicker12Hour: true,
    ranges: {
       'Today': [moment(), moment()],
       'Yesterday': [moment().subtract('days', 1), moment().subtract('days', 1)],
       'Last 7 Days': [moment().subtract('days', 6), moment()],
       'Last 30 Days': [moment().subtract('days', 29), moment()],
       'This Month': [moment().startOf('month'), moment().endOf('month')],
       'Last Month': [moment().subtract('month', 1).startOf('month'), moment().subtract('month', 1).endOf('month')]
    },
    opens: 'right',
    buttonClasses: ['btn btn-default'],
    applyClass: 'btn-small btn-primary',
    cancelClass: 'btn-small',
    format: 'MM/DD/YYYY',
    separator: ' - ',
    locale: {
        applyLabel: 'Submit',
        fromLabel: 'From',
        toLabel: 'To',
        customRangeLabel: 'Custom Range',
        daysOfWeek: ['Su', 'Mo', 'Tu', 'We', 'Th', 'Fr','Sa'],
        monthNames: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'],
        firstDay: 1
    }
  };


}
jQuery(document).ready(function(){
      $('#<?php echo $this->elementName; ?>').daterangepicker(options);
});
<?php $this->inlineScript()->captureEnd(); ?>

<div class="input-group">
  <span class="input-group-addon">
    <i class="glyphicon glyphicon-calendar fa fa-calendar"></i>
  </span>
	<input type="text" style="width: 200px" name="<?php echo $this->elementName; ?>" id="<?php echo $this->elementName; ?>" class="form-control" value="<?php echo $value; ?>" /> 
</div>